spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # or "*" to allow all origins
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # or specify headers
            allowCredentials: true
      routes:
        - id: MSBlogRecycle
          uri: lb://MSBlogRecycle
          predicates:
            - Path=/blog/**
