spring:
  cloud:
    gateway:
      discovery:
        locator:
          # lower-case-service-id: true
          enabled: true
      routes:
        - id: MSBlogRecycle
          uri: lb://MSBlogRecycle
          predicates:
            - Path=/blog/**



